### ISSUE TITLE
Use a real brewery name

### ISSUE THREAD

**Issue by akirataguchi115** [mluukkai/WebPalvelinohjelmointi2023#25]
idk if this is just stupid but could we use some Sinebrychoff instead of Koff in the example here: https://github.com/mluukkai/WebPalvelinohjelmointi2023/blob/main/english/week1.md#user-content-beers-and-the-one-to-many-connection . I think Koff is a Beer not a Brewery :beer:

**Comment by mluukkai** [comment]
will not fix

**Comment by mluukkai** [comment]
of course pr that fixes this would be nice, unfortunately there are some fake breweries and possibly also beers in pics also and that makes the fix burdensome

**Comment by akirataguchi115** [comment]
fair enough
